### ISSUE TITLE
[internalisationFilter] testRoundTripping with long-html.html is broken 

### ISSUE THREAD

**Issue by ArneBinder** [freme-project/basic-services#52]
It fails with this exception:
```
`com.mashape.unirest.http.exceptions.UnirestException: java.net.SocketTimeoutException: Read timed out

	at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:143)
	at com.mashape.unirest.request.BaseRequest.asString(BaseRequest.java:56)
	at eu.freme.bservices.filters.internationalizationfilter.InternalizationFilterTest.testRoundTripping(InternalizationFilterTest.java:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:136)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:152)
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:270)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:161)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:153)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:271)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:254)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
	at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:138)
	... 28 more

[2016-06-22 17:00:43.867] boot - 7432  INFO [Thread-1] --- AnnotationConfigEmbeddedWebApplicationContext: Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@44a664f2: startup date [Wed Jun 22 16:59:23 CEST 2016]; root of context hierarchy
[2016-06-22 17:00:43.944] boot - 7432  INFO [Thread-1] --- AnnotationMBeanExporter: Unregistering JMX-exposed beans on shutdown
[2016-06-22 17:00:44.119] boot - 7432  INFO [Thread-1] --- LocalContainerEntityManagerFactoryBean: Closing JPA EntityManagerFactory for persistence unit 'default'

Process finished with exit code -1
```

**Comment by ArneBinder** [comment]
Is this related to [this](https://github.com/freme-project/e-Internationalization/issues/9)?

**Comment by ArneBinder** [comment]
@katia-vistatec do you have any ideas on this issue? 
thanks!

**Comment by katia-vistatec** [comment]
Hi,
which unit test is it?

**Comment by ArneBinder** [comment]
It is [eu.freme.bservices.filters.internationalizationfilter.InternalizationFilterTest.testRoundTripping](http://rv1443.1blu.de:8082/job/BasicServices/264/eu.freme.bservices.filters$internationalization-filter/testReport/eu.freme.bservices.filters.internationalizationfilter/InternalizationFilterTest/testRoundTripping/).

**Comment by katia-vistatec** [comment]
Hi,
from the unit test using the long-html.html file it is a String index out of range: -6. 
![error](https://cloud.githubusercontent.com/assets/19167454/16422462/5cad759c-3d50-11e6-9a66-48081d33804e.PNG)

**Comment by katia-vistatec** [comment]
It happens when calling the substring method with the first index greater then the second. This happen in:
originalFileString.append(skeletonContext.substring(skeletonLastIdx,	tuRes.getWasConvFromStartIdx()));

**Comment by katia-vistatec** [comment]
skeletonLastIdx is 70074 and  tuRes.getWasConvFromStartIdx() is 70068.

**Comment by katia-vistatec** [comment]
I pushed the changes to the repository and now the unit test for the file /roundtripping/long-html.html works. The problem because two text units for the test case had the same wasConvFromStartIdx and wasConvFromEndIdx . For the first text unit skeletonLastIndex is updated to wasConvFromEndIdx (70074) and so for the second text unit skeletonLastIndex = 70074 and wasConvFromStartIdx= 70068 and when extracting the substring it gives an error because the first index is greater then the second.

**Comment by katia-vistatec** [comment]
There are similar problems (index out of range:-14 and index out of range:-18 ) for issue #35 and #40

**Comment by ArneBinder** [comment]
@katia-vistatec thanks a lot for this fix!
But the roundtrippingTest in the internalisation-**filter** is still broken. I still get the time out Exception mentioned above. We still have to examine, why this happens.

**Comment by katia-vistatec** [comment]
Ok. I solved another problem. I will have a look at it.

**Comment by ArneBinder** [comment]
@katia-vistatec thanks again! But do not invest to much into this, I can have a look when I'm back in office. I do not know if it is really internalisation related or just an issue of the filter.

**Comment by jnehring** [comment]
What is the status here? @ArneBinder did you take a look at this?

**Comment by ArneBinder** [comment]
It seems to be caused by [this bug](https://github.com/freme-project/basic-services/issues/59).

**Comment by jnehring** [comment]
> Should we disable the test until #59 is resolved?

No need to disable it, lets wait until it is solved.

**Comment by jnehring** [comment]
I configured JUnit to ignore the test so it does not cause trouble during the release.

**Comment by jnehring** [comment]
@ArneBinder please try to re-enable the unit test. I think it is fixed through #59

**Comment by ArneBinder** [comment]
@jnehring [The test](https://github.com/freme-project/basic-services/blob/master/filters/internationalization-filter/src/test/java/eu/freme/bservices/filters/internationalizationfilter/InternalizationFilterTest.java#L146-L157) still aborts with a timeout (at my local machine) like mentioned above.

**Comment by jnehring** [comment]
@katia-vistatec can you please test why [the unit test](https://github.com/freme-project/basic-services/blob/master/filters/internationalization-filter/src/test/java/eu/freme/bservices/filters/internationalizationfilter/InternalizationFilterTest.java#L146-L157) does get the timeout? Maybe the bug in #59 is still not fixed.

**Comment by katia-vistatec** [comment]
Hi,
It seems to me fixed. You can test it.

**Comment by jnehring** [comment]
@bgrusdt please

* Remove remove the ignore annotation from [the unit test](https://github.com/freme-project/basic-services/blob/master/filters/internationalization-filter/src/test/java/eu/freme/bservices/filters/internationalizationfilter/InternalizationFilterTest.java#L146-L157).
* Test if the unit test works on your local machine
* Test if the unit test works on jenkins

**Comment by bgrusdt** [comment]
I also get a time out for [the unit test](https://github.com/freme-project/basic-services/blob/master/filters/internationalization-filter/src/test/java/eu/freme/bservices/filters/internationalizationfilter/InternalizationFilterTest.java#L146-L157). .

**Comment by bgrusdt** [comment]
I'm sorry, I didn't have the latest updates... so it does actually work, there is no timeout anymore.

**Comment by bgrusdt** [comment]
On Jenkins, BasicServices is fine as well, so I will close this issue.
